### ISSUE TITLE
CHG rename professor display name

### ISSUE THREAD

**Issue by AlpacaMax** [GusSand/Anubis#164]
The Course model has both `professor` and `professor_for_course`. The `professor` column seems to only be the name of the professor while `professor_for_course` is a one-to-many relationship with `ProfessorForCourse` model. So `professor` looks redundant and should be removed. However, removing this column seems to be not easy as we need to:
- Change all the occurrences in the code that directly access this column
- Do a database migration on the production server, which as far as I know can only be done by @wabscale 

There's a trick for the first change. After removing `professor` column we can write a `professor` property in `Course` that returns the value `professor` column originally contains. This way we don't have to change all the occurrences in the code.

The reason I don't do a PR immediately is because I don't know if there're other side effects that I haven't considered yet.  So please let me know you thoughts @wabscale .

**Comment by wabscale** [comment]
Great eye for detail. I'm impressed that you caught this.

Let me explain what that column is. That column has been in Anubis since version v1.0.0. It should probably be called `professor_display_name` or something like that. The value in that column is what is displayed as the professor name on the course card:

![anubis-professor-display](https://user-images.githubusercontent.com/36013983/124371958-b4959e80-dc54-11eb-8613-75085ab7cdf3.png)

I see what you are saying here. I think we should stick to having the professor display name be as a separate column. The spacing on the course card is a bit touchy, so manually setting the professor last name is easiest to not break that. 

We should at least rename that column so it is a bit more clear. Maybe rename this issue to `CHG rename professor display name` or something along those lines.

**Comment by wabscale** [comment]
Also minor word on the migrations you mentioned. 

We use `alembic` for migrations. You can generate your own if you are using the [debug](https://github.com/GusSand/Anubis/blob/master/docs/development_guide.md#debug-environment) (not mindebug) environment. All the migrations are just alembic python scripts that are here in [api/migrations/versions](https://github.com/GusSand/Anubis/tree/master/api/migrations/versions). 

Then to address the thing you brought up about deployment. Right now myself, Professor Gustavo and Somto all have access to the cluster and can roll out changes (at least have the permission to). We are working on getting Teo (the new Anubis TA) the permissions to access the cluster. My point is that it is not just me that has access to the cluster (and therefore the prod database).

**Comment by AlpacaMax** [comment]
I see. Thanks for all the information.

**Comment by AlpacaMax** [comment]
Thanks for assigning this to me. I'll probably work on it later this week as I've been busy with my own stuff. Also I need to check out how alembic works.

**Comment by wabscale** [comment]
No worries. This is not mission critical right now. Take all the time you need. Thanks for all your contributions, it is much appreciated.
